# These substitutions allow the end user to override certain values
substitutions:
  name: esp32_s3_matrix
  friendly_name: esp32_s3_matrix

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: esphome.web
    version: dev

api:
  encryption:
    key: !secret api_encryption_key  # Replace with your actual encryption key

wifi:
  ssid: !secret wifi_ssid  # Replace with your actual wifi ssid
  password: !secret wifi_password  # Replace with your actual wifi password


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:


# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32s3.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

  - platform: version
    name: "ESPHome Version"

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO14
    num_leds: 64
    rgb_order: RGB
    name: "8x8 LED Matrix"
    id: led_matrix
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_flicker:
      - addressable_fireworks:
          name: Fireworks
      - addressable_lambda:
          name: "Green Tick"
          update_interval: 5s
          lambda: |-
            for (int i = 0; i < it.size(); i++) {
              it[i] = ESPColor(0, 0, 0);
            } // Clear display

            static const std::vector<uint8_t> tick = {
              7,             // row 0
              14, 15,        // row 1
              21, 22,        // row 2
              24, 28, 29,    // row 3
              32, 33, 35, 36,// row 4
              41, 42, 43,    // row 5
              50             // row 6
            };
            for (auto i : tick) {
              it[i] = ESPColor(0, 255, 0);
            }

      - addressable_lambda:
          name: "Red No Entry"
          update_interval: 5s
          lambda: |-
            for (int i = 0; i < it.size(); i++) {
              it[i] = ESPColor(0, 0, 0);
            } // Clear display

            // Red no entry
            std::vector<uint8_t> ring = {
              2, 3, 4, 5,    // row 0
              9, 14,         // row 1
              16, 21, 23,    // row 2
              24, 28, 31,    // row 3
              32, 35, 39,    // row 4
              40, 42, 47,    // row 5
              49, 54,        // row 6
              58, 59, 60, 61 // row 7
            };
            for (auto i : ring) {
              it[i] = ESPColor(255, 0, 0);  // Red
            }
