# Automatically merge Dependabot PRs when version comparison is within the range
# that is configured in .github/auto-merge.yml

name: Auto-Merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-merge:
    # Only act if Dependabot opened the PR
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    concurrency:
      group: dependabot-automerge-${{ github.event.pull_request.number }}
      cancel-in-progress: false

    steps:
      - name: Guardrail — ensure ACCESS_TOKEN is set
        if: ${{ !secrets.ACCESS_TOKEN }}
        run: |
          echo "ACCESS_TOKEN is missing. Define it in Settings > Secrets and variables > Actions."
        run: |
          if [ -z "${ACCESS_TOKEN}" ]; then
            echo "ACCESS_TOKEN is missing. Define it in Settings > Secrets and variables > Actions."
            exit 1
          fi

      - name: Dependabot Auto-Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}   # fine-scoped PAT with repo perms
          command: squash and merge
